pom.xml
streamx-flink/streamx-flink-core/pom.xml
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/sink/ClickHouseJDBCSink.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/flink/test/ClickhouseSinkApp.scala

clickhousesink提交

---

streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkDataSet.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkStreaming.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkTable.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/ClickHouseSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/ConnectorApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/DashboardApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/FlinkSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/HBaseSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/HBaseSourceApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/InfluxDBSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/JdbcSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/KafkaSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/KafkaSourceApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/MongoSourceApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/MySQLSourceApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/PolestarDashboardApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/SideOutApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/StreamingTestApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/TransformationsApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/tablesql/FileTableApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/tablesql/HelloFlinkSQL.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/tablesql/KafkaTableApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/tablesql/MySQLCDC.scala

rename method "handler" to "handle"

rename method "handler" to "handle"

---

streamx-console/streamx-console-webapp/package-lock.json
streamx-console/streamx-console-webapp/src/views/flink/app/View.vue

metrics dashboard support!

---

pom.xml
streamx-common/src/main/scala/com/streamxhub/common/conf/ConfigConst.scala
streamx-console/streamx-console-service/src/main/java/com/streamxhub/console/core/entity/Application.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-webapp/package-lock.json
streamx-console/streamx-console-webapp/src/views/flink/app/View.vue
streamx-flink/streamx-flink-core/pom.xml
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkInitializer.scala
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/interpreter/FlinkExprTyper.scala
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/interpreter/FlinkILoopInterpreter.scala
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/interpreter/FlinkScalaInterpreter.scala
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/interpreter/FlinkShell.scala
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/interpreter/InterpreterOutput.scala
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/interpreter/InterpreterResult.scala
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/interpreter/JobManager.scala
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/shims/FlinkShims.java
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/shims/FlinkVersion.java
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/util/DependencyUtils.scala
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/util/HadoopUtils.java
streamx-flink/streamx-flink-submit/src/main/scala/com/streamxhub/flink/submit/FlinkSubmit.scala
streamx-plugins/jvm-profiler/pom.xml

flameGraph support!

---

streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/request/HBaseRequest.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/request/MySQLRequest.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/HBaseSourceApp.scala

HBaseRequest MysqlRequest 返回原始数据

HBaseRequest MysqlRequest 返回原始数据

---

README.md
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/java/function/HBaseFunction.java
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/java/function/MongoFunction.java
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/java/function/SQLGetFunction.java
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/java/source/MongoSource.java
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/source/HBaseSource.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/source/MongoSource.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/source/MySQLSource.scala
streamx-flink/streamx-flink-test/pom.xml
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/HBaseTestApp.scala

Source return last one

---

pom.xml
streamx-flink/pom.xml
streamx-flink/streamx-flink-cli/pom.xml
streamx-flink/streamx-flink-cli/src/main/scala/com/streamxhub/flink/cli/FlinkTableCli.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/request/HBaseRequest.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/request/MySQLRequest.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/source/HBaseSource.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/source/MongoSource.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/source/MySQLSource.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/HBaseTestApp.scala

HBaseRequest bug fix

---

pom.xml
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/request/JdbcRequest.scala

MySQLRequest rename to JdbcRequest

MySQLRequest rename to JdbcRequest

---

streamx-flink/streamx-flink-cli/src/main/scala/com/streamxhub/flink/cli/FlinkTableCli.scala
streamx-flink/streamx-flink-cli/src/main/scala/com/streamxhub/flink/cli/SQLCommandUtil.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkStreamTable.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkStreaming.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkTable.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/util/FlinkInitializer.scala
streamx-flink/streamx-flink-test/assembly/conf/application.yml
streamx-flink/streamx-flink-test/src/main/java/com/streamxhub/flink/javacase/KafkaJavaApp.java
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/stream/KafkaSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/tablesql/FileTableApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/tablesql/HelloFlinkSQL.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/tablesql/KafkaTableApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/tablesql/MySQLCDC.scala

 sql submit support

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/console/core/metrics/flink/JvmProfiler.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/console/core/service/impl/ProjectServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/console/core/service/impl/SavePointServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/console/core/task/FlinkTrackingTask.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/console/core/task/MetricsTask.java
streamx-console/streamx-console-webapp/package-lock.json
streamx-console/streamx-console-webapp/package.json

axios upgrade

---

pom.xml
streamx-flink/streamx-flink-core/pom.xml
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/java/source/KafkaSource.java
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkStreamTable.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkStreaming.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkTable.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/sink/ClickHouseSink.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/sink/EchoSink.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/sink/HBaseSink.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/sink/JdbcSink.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/sink/KafkaSink.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/sink/RedisSink.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/source/KafkaSource.scala
streamx-flink/streamx-flink-submit/src/main/scala/com/streamxhub/flink/submit/FlinkSubmit.scala
streamx-flink/streamx-flink-test/assembly/conf/application.yml
streamx-flink/streamx-flink-test/pom.xml
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/tablesql/KafkaTableApp.scala

1) flink upgrade 1.20.0
2) StreamTableContext 中 流和批API融合

flink upgrade 1.20.0

---

streamx-console/streamx-console-service/pom.xml
streamx-console/streamx-console-service/src/main/java/com/streamxhub/console/core/service/impl/ApplicationServiceImpl.java
streamx-flink/streamx-flink-cli/pom.xml
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/FlinkStreaming.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/flink/core/scala/sink/HBaseSink.scala
streamx-flink/streamx-flink-repl/pom.xml
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/interpreter/FlinkScalaInterpreter.scala
streamx-flink/streamx-flink-repl/src/main/scala/com/streamxhub/repl/flink/interpreter/FlinkShell.scala
streamx-flink/streamx-flink-submit/src/main/scala/com/streamxhub/flink/submit/FlinkSubmit.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/test/tablesql/KafkaTableApp.scala
streamx-plugins/jvm-profiler/pom.xml

flink upgrade 1.12.0

---

README.md
pom.xml
streamx-console/pom.xml
streamx-console/streamx-console-service/pom.xml

core format with spotless

---

streamx-console/streamx-console-webapp/package.json

mavon-editor update

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/conf/ConfigConst.scala
streamx-console/streamx-console-service/pom.xml
streamx-console/streamx-console-service/src/assembly/assembly.xml
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/Application.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/JobType.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/system/runner/EnvInitializeRunner.java
streamx-console/streamx-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
streamx-console/streamx-console-webapp/src/views/flink/app/Add.vue
streamx-console/streamx-console-webapp/src/views/flink/app/View.vue
streamx-flink/streamx-flink-cli/pom.xml
streamx-flink/streamx-flink-cli/src/main/scala/com/streamxhub/streamx/flink/cli/FlinkTableCli.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/FlinkStreamTable.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/util/FlinkStreamingInitializer.scala
streamx-flink/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/FlinkSubmit.scala
streamx-flink/streamx-flink-test/assembly/conf/application.yml
streamx-spark/streamx-spark-cli/create_app.sh
streamx-spark/streamx-spark-test/assembly.xml

flink SQL submit support

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-service/src/main/resources/flink-application.template
streamx-console/streamx-console-webapp/src/views/flink/app/Add.vue
streamx-console/streamx-console-webapp/src/views/flink/app/Detail.vue
streamx-flink/streamx-flink-core/src/main/java/org/apache/flink/table/api/internal/OverrideTableEnvironmentImpl.java
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/FlinkStreamTable.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/util/FlinkStreamingInitializer.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/util/FlinkTableInitializer.scala
streamx-flink/streamx-flink-core/src/main/scala/org/apache/flink/table/api/bridge/scala/OverrideStreamTableEnvironment.scala
streamx-flink/streamx-flink-core/src/main/scala/org/apache/flink/table/api/bridge/scala/internal/OverrideStreamTableEnvironmentImpl.scala

1)flink SQL submit support!
2)flink SQL支持自定义job Name

flink SQL submit support!

---

pom.xml
streamx-common/src/main/scala/com/streamxhub/streamx/common/enums/DevelopmentMode.java
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/DependencyUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HdfsUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/RedisEndpoint.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/RedisUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/SQLCommandUtil.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/FlinkStreamTable.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/FlinkStreaming.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/FlinkTable.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/ClickHouseSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/ConnectorApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/DashboardApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/FlinkSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/HBaseSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/HBaseSourceApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/HBaseTestApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/InfluxDBSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/JdbcSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/KafkaSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/KafkaSourceApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/MongoSourceApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/MySQLSourceApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/PolestarDashboardApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/SideOutApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/StreamingTestApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/tablesql/FileTableApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/tablesql/HelloFlinkSQL.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/tablesql/KafkaTableApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/tablesql/MySQLCDC.scala

flink sql submit完成

---

streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/request/JdbcRequest.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/JdbcSinkApp.scala
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/KafkaSourceApp.scala

修复 jdbcRequest bug

---

streamx-flink/streamx-flink-common/src/main/scala/com/streamxhub/streamx/flink/common/util/SQLCommandUtil.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/util/FlinkTableTrait.scala

download maven dependency bug fixed!

---

streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/util/FlinkTableTrait.scala

sql parser bug fixed

---

streamx-plugin/streamx-flink-sqlcli/pom.xml
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/trait/FlinkSubmitTrait.scala

common jar path error,fixed

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/AlertServiceImpl.java

fault alert support

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/dao/EffectiveMapper.java

delete effective bug fixed

---

README.md
README_CN.md
streamx-console/streamx-console-webapp/src/views/flink/app/Add.vue
streamx-console/streamx-console-webapp/src/views/flink/app/EditFlink.vue
streamx-console/streamx-console-webapp/src/views/flink/app/EditStreamX.vue

readme i18n 

---

README.md
streamx-common/src/main/scala/com/streamxhub/streamx/common/conf/ConfigConst.scala
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/system/runner/StartedUpRunner.java
streamx-console/streamx-console-service/src/main/resources/banner.txt

readme i18n

---

streamx-console/streamx-console-service/pom.xml
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/SettingServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/task/FlinkTrackingTask.java
streamx-console/streamx-console-service/src/main/resources/application-dev.yml
streamx-console/streamx-console-service/src/main/resources/application-prod.yml
streamx-console/streamx-console-service/src/main/resources/db/migration/V1_0__init_db.sql
streamx-console/streamx-console-service/src/main/resources/db/migration/V1_1__init_data.sql
streamx-console/streamx-console-webapp/pom.xml

Feature:add flyway

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/SavePointServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/task/FlinkTrackingTask.java
streamx-console/streamx-console-service/src/main/resources/db/migration/V1_0__init_db.sql
streamx-console/streamx-console-webapp/src/views/user/SignIn.vue

fayway support and slogan changed.

fayway support and slogan changed.

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/conf/ConfigConst.scala
streamx-flink/streamx-flink-common/src/main/scala/com/streamxhub/streamx/flink/common/conf/ParameterCli.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/util/FlinkStreamingInitializer.scala
streamx-flink/streamx-flink-test/assembly/bin/flink.sh
streamx-flink/streamx-flink-test/src/main/scala/com/streamxhub/streamx/test/stream/ParameterCliApp.scala

startup script parse parameter bug fixed.

startup script parse parameter bug fixed.

---

streamx-console/streamx-console-service/src/main/resources/db/migration/V1_0__init_db.sql
streamx-flink/streamx-flink-test/assembly/bin/flink.sh

shell script parse bug fixed.

---

streamx-console/streamx-console-webapp/src/views/flink/app/Detail.vue
streamx-console/streamx-console-webapp/src/views/flink/project/Add.vue

startlog detail bug fixed

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/Application.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/task/FlinkTrackingTask.java
streamx-console/streamx-console-webapp/src/views/flink/app/Add.vue
streamx-console/streamx-console-webapp/src/views/flink/app/Detail.vue
streamx-console/streamx-console-webapp/src/views/flink/app/Different.vue
streamx-console/streamx-console-webapp/src/views/flink/app/EditStreamX.vue
streamx-console/streamx-console-webapp/src/views/flink/app/Mergely.vue
streamx-console/streamx-console-webapp/src/views/flink/setting/View.vue

flink app state bug fixed

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/controller/SettingController.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/system/controller/RoleController.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/system/controller/UserController.java
streamx-console/streamx-console-service/src/main/resources/db/migration/V1_1__init_data.sql
streamx-console/streamx-console-webapp/src/api/index.js
streamx-console/streamx-console-webapp/src/api/setting.js
streamx-console/streamx-console-webapp/src/store/getters.js
streamx-console/streamx-console-webapp/src/views/flink/app/View.vue
streamx-console/streamx-console-webapp/src/views/system/menu/Menu.vue
streamx-console/streamx-console-webapp/src/views/system/role/Role.vue
streamx-console/streamx-console-webapp/src/views/system/user/User.vue

permission related logic adjustment and bug fixed.

permission related logic adjustment and bug fixed.

---

streamx-flink/streamx-flink-core_flink-1.13/src/main/scala/com/streamxhub/streamx/flink/core/scala/util/FlinkStreamingInitializer.scala

flink 1.13 set RocksDBStateBackend bug fixed

flink 1.13 support

---

README.md

Add a quick start introduction to the readme file

Added quick start introduction

---

README.md

Prerequisites for building

---

README.md
README_CN.md

readme join us bug fixed.

---

README.md
README_CN.md

readme theme change support.

---

README.md
README_CN.md
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/Application.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/AppExistsState.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/ApplicationType.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/CandidateType.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/ChangedType.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/CheckPointType.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/DeployState.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/FlinkAppState.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/GitAuthorizedError.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/OptionState.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/metrics/flink/CheckPoints.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/AlertService.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/ApplicationService.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/AlertServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/task/FlinkTrackingTask.java
streamx-console/streamx-console-service/src/main/resources/mapper/core/ApplicationMapper.xml
streamx-console/streamx-console-webapp/package.json
streamx-console/streamx-console-webapp/src/views/flink/app/Add.vue
streamx-console/streamx-console-webapp/src/views/flink/app/EditFlink.vue
streamx-console/streamx-console-webapp/src/views/flink/app/EditStreamX.vue
streamx-console/streamx-console-webapp/src/views/user/SignIn.vue

[New Feature] checkPoint Failure Options (sent email or restart)

[New Feature] checkPoint Failure Options (sent email or restart)

---

streamx-console/streamx-console-service/src/main/resources/email.html
streamx-console/streamx-console-service/src/test/java/SendEmailTest.java

[Optimize] alarm email template optimization

[Optimize] alarm email template optimization

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/Application.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/metrics/flink/MailTemplate.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/AlertServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-service/src/main/resources/email.html
streamx-console/streamx-console-service/src/test/java/SendEmailTest.java
streamx-console/streamx-console-webapp/src/views/flink/app/Add.vue
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/SqlCommandParser.scala

[BugFix] flink sql create view bug fixed, send email bug fixed

[BugFix] flink sql create view bug fixed, send email bug fixed

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/AlertServiceImpl.java

[BugFix] send email bug fixed

---

streamx-console/streamx-console-service/pom.xml
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/Application.java
streamx-parent/pom.xml
streamx-plugin/streamx-flink-repl/pom.xml
streamx-plugin/streamx-flink-submit/pom.xml

maven dependency optimize

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/conf/ConfigConst.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/ClassLoaderUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/FileUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HttpClientUtils.scala
streamx-console/streamx-console-service/pom.xml
streamx-console/streamx-console-service/src/assembly/assembly.xml
streamx-console/streamx-console-service/src/assembly/bin/startup.sh
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/controller/FlinkSqlController.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/runner/EnvInitializeRunner.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/FlinkSqlService.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/FlinkSqlServiceImpl.java
streamx-console/streamx-console-service/src/test/java/RegexTest.java
streamx-console/streamx-console-service/src/test/java/SQLCommandTest.java
streamx-console/streamx-console-service/src/test/java/YarnTest.java
streamx-flink/streamx-flink-core/pom.xml
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/FlinkStreamTableTrait.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/FlinkTableHelper.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/FlinkTableTrait.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims_flink-1.12/src/main/scala/com/streamxhub/streamx/flink/core/SqlValidator.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims_flink-1.13/src/main/scala/com/streamxhub/streamx/flink/core/SqlValidator.scala
streamx-parent/pom.xml
streamx-plugin/streamx-flink-repl/pom.xml
streamx-plugin/streamx-flink-sqlclient/src/main/scala/com/streamxhub/streamx/flink/cli/SqlClient.scala
streamx-plugin/streamx-jvm-profiler/pom.xml

[Optimization] Flink multi version support optimization!

[Optimization] Flink multi version support optimization!

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/util/ConfigUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/PropertiesUtils.scala
streamx-console/streamx-console-webapp/src/views/flink/app/Add.vue
streamx-console/streamx-console-webapp/src/views/flink/app/EditFlink.vue
streamx-console/streamx-console-webapp/src/views/flink/app/EditStreamX.vue
streamx-flink/streamx-flink-core/src/main/java/com/streamxhub/streamx/flink/core/java/source/HBaseSource.java
streamx-flink/streamx-flink-core/src/main/java/com/streamxhub/streamx/flink/core/java/source/JdbcSource.java
streamx-flink/streamx-flink-core/src/main/java/com/streamxhub/streamx/flink/core/java/source/MongoSource.java
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/failover/ThresholdConf.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/request/HBaseRequest.scala
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/source/HBaseSource.scala
streamx-spark/streamx-spark-core/src/main/scala/com/streamxhub/streamx/spark/core/SparkStreaming.scala

prompt message syntax error correction

prompt message syntax error correction

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala
streamx-console/streamx-console-service/pom.xml
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-webapp/src/views/flink/app/View.vue
streamx-parent/pom.xml
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/ApplicationSubmit.scala

[BugFix] flink sql dependency download error bug fixe

[BugFix] flink sql dependency download error bug fixe

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/util/ClassLoaderUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/PropertiesUtils.scala
streamx-console/streamx-console-service/pom.xml
streamx-console/streamx-console-service/src/assembly/bin/startup.sh
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/controller/ApplicationController.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/controller/FlinkSqlController.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/runner/EnvInitializeRunner.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/FlinkSqlServiceImpl.java
streamx-console/streamx-console-service/src/main/resources/application-prod.yml
streamx-console/streamx-console-service/src/main/resources/logback-spring.xml
streamx-console/streamx-console-service/src/test/java/SQLCommandTest.java
streamx-console/streamx-console-webapp/src/views/flink/app/Detail.less
streamx-console/streamx-console-webapp/src/views/flink/app/Detail.vue
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/conf/ParameterCli.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/FlinkSqlExecutor.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/FlinkStreamTableTrait.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/FlinkTableTrait.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims_flink-1.12/src/main/scala/com/streamxhub/streamx/flink/core/FlinkSqlValidator.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims_flink-1.13/src/main/scala/com/streamxhub/streamx/flink/core/FlinkSqlValidator.scala
streamx-parent/pom.xml
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/ApplicationSubmit.scala
streamx-spark/streamx-spark-cli/create_app.sh

[BugFix] issues 186,202 bug fixed.

[BugFix] issues 186,202 bug fixed.

---

streamx-parent/pom.xml

解决streamx-parent maven dependency问题（中央仓库Jar依赖变动导致），并测试构建成功（Build Success）

fix: streamx-parent maven dependency

---

pom.xml
streamx-common/pom.xml
streamx-common/src/main/scala/com/streamxhub/streamx/common/conf/ConfigConst.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HdfsUtils.scala
streamx-console/pom.xml
streamx-console/streamx-console-service/pom.xml
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/task/FlinkTrackingTask.java
streamx-console/streamx-console-service/src/main/resources/db/migration/V1_1__init_data.sql
streamx-console/streamx-console-service/src/main/resources/kerberos.yml
streamx-console/streamx-console-service/src/test/java/RefreshCacheTest.java
streamx-console/streamx-console-webapp/pom.xml
streamx-flink/pom.xml
streamx-flink/streamx-flink-core/pom.xml
streamx-flink/streamx-flink-shims/pom.xml
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/pom.xml
streamx-flink/streamx-flink-shims/streamx-flink-shims_flink-1.12/pom.xml
streamx-flink/streamx-flink-shims/streamx-flink-shims_flink-1.13/pom.xml
streamx-flink/streamx-flink-test/pom.xml
streamx-parent/pom.xml
streamx-plugin/pom.xml
streamx-plugin/streamx-flink-repl/pom.xml
streamx-plugin/streamx-flink-sqlclient/pom.xml
streamx-plugin/streamx-flink-submit/pom.xml
streamx-plugin/streamx-flink-udf/pom.xml
streamx-plugin/streamx-jvm-profiler/pom.xml
streamx-spark/pom.xml
streamx-spark/streamx-spark-cli/pom.xml
streamx-spark/streamx-spark-core/pom.xml
streamx-spark/streamx-spark-test/pom.xml

Update version to 1.1.0

---

README.md
README_CN.md

- Please test it, then submit.

streamx 1.1.0 release

---

README.md
README_CN.md
streamx-common/src/main/scala/com/streamxhub/streamx/common/conf/ConfigConst.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/CommandUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/Utils.scala
streamx-console/streamx-console-service/src/main/resources/kerberos.yml
streamx-console/streamx-console-service/src/test/java/RefreshCacheTest.java
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/ApplicationSubmit.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/YarnPreJobSubmit.scala

[bugfix]kerberos relogin bug fixed

[bugfix]kerberos relogin bug fixed

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala
streamx-console/streamx-console-service/src/main/resources/application-dev.yml
streamx-console/streamx-console-service/src/main/resources/application-prod.yml
streamx-console/streamx-console-service/src/test/java/RegexTest.java
streamx-console/streamx-console-webapp/package.json

antdv update to 1.7.6

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java

eg. exceptions occured, assert failed, might be other conditions as well.
Fixes Issue #218.

fix bug: all records in app table may be overwritten during deploy under some conditions

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/FlinkSubmit.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/YarnApplicationSubmit.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/trait/FlinkSubmitTrait.scala

[bugfix]kerberos relogin bug fixed.

[bugfix]kerberos relogin bug fixed.

---

streamx-console/streamx-console-webapp/src/views/flink/app/EditFlink.vue
streamx-console/streamx-console-webapp/src/views/flink/app/EditStreamX.vue
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/YarnApplicationSubmit.scala

[bugfix] parallelism and slot parameter bug fixed

[bugfix] parallelism and slot parameter bug fixed

---

streamx-console/streamx-console-service/src/main/resources/db/migration/V1_1_1__upgrade_db.sql

[bugfix] V1_1_1 upgrade db

---

streamx-console/streamx-console-webapp/src/views/flink/setting/View.vue

[bugfix] mainClass bug fixed.

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/AlertServiceImpl.java

[bugfix] sent email bug fixed.

[bugfix] sent email bug fixed.

---

streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/source/KafkaSource.scala

[bugfix] KafkaSource topic no matching type when parsing[#242]

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/util/SqlConvertUtils.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/SqlCommandParser.scala
streamx-flink/streamx-flink-test/assembly/conf/sql.yml

[bugfix] flinkSql verify bug #265

[bugfix] flinkSql verify bug #265

---

.gitignore
streamx-plugin/streamx-flink-submit/pom.xml
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/KubernetesNativeSessionSubmit.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/trait/KubernetesNativeSubmitTrait.scala

build fat-jar before submitting flink job on k8s-session mode

---

.gitignore
streamx-codebuild/pom.xml
streamx-codebuild/src/main/scala/com/streamxhub/streamx/codebuild/DockerRetriver.scala
streamx-codebuild/src/main/scala/com/streamxhub/streamx/codebuild/DockerTool.scala
streamx-codebuild/src/main/scala/com/streamxhub/streamx/codebuild/FlinkDockerfileTemplate.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/conf/K8sConfigConst.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/Utils.scala
streamx-plugin/streamx-flink-submit/pom.xml
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/KubernetesNativeSessionSubmit.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/trait/KubernetesNativeSubmitTrait.scala

Add Docker Image Build Tools

---

README.md
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/SqlConvertUtils.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/SqlCommandParser.scala
streamx-flink/streamx-flink-test/assembly/conf/sql.yml

Thank you for contributing to StreamX 😃!
[bugfix] create TEMPORARY view bug fixed #273
Issue Number: close #273

[bugfix] create TEMPORARY view bug fixed #273

---

streamx-console/streamx-console-webapp/src/utils/request.js

[hotfix] file upload request parameters bug fixed.
[hotfix] file upload request parameters bug fixed.
How it Works:

[hotfix] file upload request parameters bug fixed.

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/enums/ExecutionMode.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/runner/EnvInitializer.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/SettingServiceImpl.java
streamx-console/streamx-console-webapp/src/views/flink/app/Add.vue
streamx-plugin/streamx-flink-packer/src/test/scala/com/streamxhub/streamx/flink/packer/MavenToolSpec.scala

* Missing clusterId  when submit flink k8s-job
* Application name failed to determine for k8s execution
* Force the creation of temporary processing of the LFS workspace at boot time

streamx-console: k8s adaptation bug fix

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/util/Utils.scala
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/FlinkAppState.java
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/DefaultFlinkTrackMonitor.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/FlinkTrackCachePool.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/FlinkTrackConf.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/FlinkTrackMonitor.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/KubernetesRetriever.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/enums/FlinkJobState.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/enums/FlinkK8sExecuteMode.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/model/FlinkMetricCV.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/model/JobStatusCV.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/model/K8sDeploymentEventCV.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/model/K8sEventKey.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/model/TrackId.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/model/TrackIdCV.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/watcher/FlinkJobStatusWatcher.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/watcher/FlinkK8sEventWatcher.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/watcher/FlinkMetricWatcher.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/watcher/FlinkWatcher.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/KubernetesNativeSessionSubmit.scala

metrics & status tracking support for flink-k8s-mode

metrics & status tracking support for flink-k8s-mode

---

README.md
README_CN.md
streamx-console/streamx-console-webapp/src/views/flink/app/Add.vue
streamx-console/streamx-console-webapp/src/views/flink/app/EditStreamX.vue

[hotfix] jar file verify bug fixed

[hotfix] jar file verify bug fixed

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/conf/ConfigConst.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/conf/Workspace.scala
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/Application.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/ApplicationBackUp.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/Project.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/runner/EnvInitializer.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/SettingService.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationBackUpServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/SavePointServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/SettingServiceImpl.java
streamx-console/streamx-console-service/src/main/resources/application.yml
streamx-console/streamx-console-webapp/src/views/flink/setting/View.vue
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/maven/MavenRetriever.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/maven/MavenTool.scala
streamx-plugin/streamx-flink-packer/src/test/scala/com/streamxhub/streamx/flink/packer/MavenToolSpec.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/FlinkSubmitHelper.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/domain/SubmitRequest.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/KubernetesNativeApplicationSubmit.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/KubernetesNativeSessionSubmit.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/YarnApplicationSubmit.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/YarnPreJobSubmit.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/trait/FlinkSubmitTrait.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/trait/KubernetesNativeSubmitTrait.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/trait/YarnSubmitTrait.scala

refactoring workspace logic,better adaptive local package build, on yarn and on k8s
How it Works:
1. new class Workspace, better adaptive local package build, on yarn and on k8s
2. remove "streamx.console.workspace" from webUI(settings)

refactoring workspace logic,better adaptive local package build, on yarn and on k8s

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/conf/Workspace.scala
streamx-common/src/main/scala/com/streamxhub/streamx/common/fs/FsOperator.scala
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/Application.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/ApplicationBackUp.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/Project.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/runner/EnvInitializer.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/SettingServiceImpl.java
streamx-console/streamx-console-service/src/main/resources/db/migration/V1_2__upgrade_db.sql
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/event/FlinkJobOperaEvent.scala
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/model/K8sDeploymentEventCV.scala
streamx-plugin/streamx-flink-kubernetes/src/test/scala/com/streamxhub/streamx/flink/kubernetes/K8sFlinkTrkMonitorLazyStartTest.scala
streamx-plugin/streamx-flink-kubernetes/src/test/scala/com/streamxhub/streamx/flink/kubernetes/K8sFlinkTrkMonitorTracingTest.scala
streamx-plugin/streamx-flink-kubernetes/src/test/scala/com/streamxhub/streamx/flink/kubernetes/K8sFlinkTrkMonitorTrackingTest.scala
streamx-plugin/streamx-flink-kubernetes/src/test/scala/com/streamxhub/streamx/flink/kubernetes/SingleTrackingTaskTest.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/maven/MavenRetriever.scala
streamx-plugin/streamx-flink-repl/src/main/scala/com/streamxhub/streamx/flink/repl/interpreter/FlinkInterpreter.scala
streamx-plugin/streamx-flink-repl/src/main/scala/com/streamxhub/streamx/flink/repl/interpreter/FlinkScalaInterpreter.scala
streamx-plugin/streamx-flink-repl/src/main/scala/com/streamxhub/streamx/flink/repl/shims/FlinkVersion.java
streamx-plugin/streamx-flink-repl/src/test/java/com/streamxhub/streamx/flink/repl/test/FlinkInterpreterTest.java
streamx-plugin/streamx-flink-repl/src/test/resources/log4j.properties
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/domain/SubmitRequest.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/impl/YarnApplicationSubmit.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/trait/KubernetesNativeSubmitTrait.scala
streamx-plugin/streamx-flink-submit/src/main/scala/com/streamxhub/streamx/flink/submit/trait/YarnSubmitTrait.scala
streamx-plugin/streamx-flink-submit/src/test/scala/com/streamxhub/streamx/flink/submit/test/YarnPreJobTestCase.scala
streamx-plugin/streamx-flink-udf/src/main/scala/com/streamxhub/streamx/flink/udf/UDF.scala

1. workspace optimization,
2. spelling correction of some words
How it Works:

workspace optimization,spelling correction of some words

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/util/SqlSplitter.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/SqlCommandParser.scala
streamx-flink/streamx-flink-test/streamx-flink-test-tablesql/src/main/scala/com/streamxhub/streamx/test/flink/scala/tablesql/SqlParseTest.scala

Issue Number: close #399 
What's Changed: 
- add SqlSplitter.scala file
- replace com.streamxhub.streamx.flink.core.SqlCommandParser#parseSQL sql split logic
How it Works:
- com.streamxhub.streamx.test.flink.scala.tablesql.SqlParseTest

[Improve] - optimize the sql parse tool

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/task/FlinkTrackingTask.java
streamx-flink/streamx-flink-core/src/main/scala/com/streamxhub/streamx/flink/core/scala/source/KafkaSource.scala

-  kafka source bug fixed.
How it Works:

kafka source bug fixed.

---

pom.xml
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/SqlCommandParser.scala

- 清理遗留的老版本SQL切分逻辑，完全使用最新的SqlSplitter进行SQL切分
How it Works:

[hotfix] - resolve the sql parse conflict

---

streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/FlinkSqlExecutor.scala
streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/SqlCommandParser.scala

- 保留用户提交的SQL原始行号， 方便用户遇到SQL执行报错时定位问题
How it Works:

[Improve] keep user sql origin line number

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/fs/LFsOperator.scala

- Lfs move file bug fixed.
How it Works:

Lfs move file bug fixed.

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala

What's Changed:  webapp.address retrieve changed.
How it Works: When yarn.resourcemanager.webapp.address does not exist, it is then retrieved by yarn.resourcemanager.hostname

webapp.address retrieve 

---

streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/docker/DockerTool.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/docker/package.scala
streamx-plugin/streamx-flink-submit/streamx-flink-submit-core/src/main/scala/com/streamxhub/streamx/flink/submit/impl/KubernetesNativeApplicationSubmit.scala

Hot Fix: Stuck when building oversized images on k8s-custom-code

---

README.md
README_CN.md
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/ChangeEventBus.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/docker/DockerRetriever.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/docker/DockerTool.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/maven/MavenTool.scala

readme and Copyright update
- readme and copyright update
- log prefix cleanup.
How it Works:

readme and copyright update

---

README.md
README_CN.md
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/controller/ProjectController.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/controller/SettingController.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/ProjectService.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/SettingService.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ProjectServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/SettingServiceImpl.java
streamx-console/streamx-console-webapp/src/views/flink/project/View.vue
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/ChangeEventBus.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/docker/DockerRetriever.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/docker/DockerTool.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/maven/MavenTool.scala

build project state bug fixed.
- build project state bug fixed.
- more explicit exception information
- readme update.
How it Works:

build project state bug fixed.

---

README.md
README_CN.md
streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/controller/ProjectController.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/controller/SettingController.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/runner/EnvInitializer.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/ProjectService.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/SettingService.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ProjectServiceImpl.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/SettingServiceImpl.java
streamx-console/streamx-console-service/src/main/resources/application.yml
streamx-console/streamx-console-webapp/package-lock.json
streamx-console/streamx-console-webapp/src/views/flink/project/View.vue
streamx-plugin/streamx-flink-kubernetes/src/main/scala/com/streamxhub/streamx/flink/kubernetes/ChangeEventBus.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/docker/DockerRetriever.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/docker/DockerTool.scala
streamx-plugin/streamx-flink-packer/src/main/scala/com/streamxhub/streamx/flink/packer/maven/MavenTool.scala
streamx-plugin/streamx-flink-submit/streamx-flink-submit-core/src/main/scala/com/streamxhub/streamx/flink/submit/impl/KubernetesNativeApplicationSubmit.scala
streamx-plugin/streamx-flink-submit/streamx-flink-submit-core/src/main/scala/com/streamxhub/streamx/flink/submit/impl/KubernetesNativeSessionSubmit.scala

HADOOP_USER_NAME configurable support.
- HADOOP_USER_NAME configurable support.
- project build state bug fixed.
How it Works:

HADOOP_USER_NAME configurable support.

---

streamx-console/streamx-console-webapp/src/api/index.js
streamx-console/streamx-console-webapp/src/api/setting.js
streamx-console/streamx-console-webapp/src/views/flink/app/View.vue

[hotfix]remove "workspace" environment check from the front end.
- [hotfix]remove "workspace" environment check from the front end.
How it Works:

[hotfix]remove "workspace" environment check from the front end.

---

.github/workflows/maven.yml

Add Maven package test CI

---

.github/workflows/maven.yml

Update maven package test ci

---

streamx-console/streamx-console-service/src/main/resources/db/migration/V1_2__upgrade_db.sql

修改ddl。不应该写死数据库名字，如果用户自定义数据库名字，将会出错
How it Works:

修改ddl。不应该写死db name

---

streamx-console/streamx-console-service/src/main/resources/spy.properties

Modify spy.properties garbled comments

修改spy.properties乱码注释

---

streamx-common/src/main/scala/com/streamxhub/streamx/common/domain/FlinkVersion.scala
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/FlinkEnv.java

Issue Number: close #447   
Problem Summary: get illegal flink version while serialize FlinkEnv.class
What's Changed: enhance robustness of get flink version

[Fix-447][console-service] enhance robustness of get flink version

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/entity/Application.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/enums/ResourceFrom.java
streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java
streamx-console/streamx-console-webapp/src/components/Notice/Notice.vue
streamx-console/streamx-console-webapp/src/core/prototype.js
streamx-console/streamx-console-webapp/src/views/flink/app/View.vue
streamx-console/streamx-console-webapp/src/views/flink/project/View.vue

add new upload-local-job bug fixed.
How it Works:

[hotfix] add new upload-local-job bug fixed.

---

streamx-console/streamx-console-webapp/src/views/flink/app/Add.vue

Issue Number: https://github.com/streamxhub/streamx/issues/505
How it Works:
Describe：
In the add job form item "Execution Mode" select "kubernetes application", fill in other information, the form verification does not call back
在添加作业表单项“Execution Mode” 选择 “kubernetes application” ，填完其他信息，表单验证不回调

fix Form.validateFields callback does not execute problem

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/service/impl/ApplicationServiceImpl.java

How it Works:
Reference list request, fix the duration value

Refer to the list request and fix the duration value

---

streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/task/K8sFlinkChangeEventListener.java

Issue Number: https://github.com/streamxhub/streamx/issues/500
How it Works:
fix the endTime value

fix the endTime value
